name: mobimart_app
description: "A new Flutter e-commerce project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+4

  # Core UI
  cupertino_icons: ^1.0.8

  # Navigation & state management
  provider: ^6.0.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.8.0
  firebase_storage: ^11.6.0

  # Utilities
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  http: ^1.6.0
  uuid: ^3.0.7
  url_launcher: ^6.2.10

  # UI & Effects
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  iconly: ^1.0.1
  flutter_launcher_icons: ^0.14.4
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/mobimart.png
    - assets/images/user_placeholder.png
    - assets/icons/app_icon.png
    - assets/images/banners/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
