// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwkbs224q8pKWwkHjSQ6mTnxMtwiPG34Y',
    appId: '1:580060550825:web:b36e6911a6b08aa6d67bb8',
    messagingSenderId: '580060550825',
    projectId: 'mobimart-b80a2',
    authDomain: 'mobimart-b80a2.firebaseapp.com',
    storageBucket: 'mobimart-b80a2.firebasestorage.app',
    measurementId: 'G-K43HZTKCHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsS7t3ApdpGalD8o6HjF4a27V680spqc4',
    appId: '1:580060550825:android:13d98f1f805cb24fd67bb8',
    messagingSenderId: '580060550825',
    projectId: 'mobimart-b80a2',
    storageBucket: 'mobimart-b80a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlgJfzNwZcvFPKQAovCll24jsJK1k4-Hw',
    appId: '1:580060550825:ios:80dc606f8df9c072d67bb8',
    messagingSenderId: '580060550825',
    projectId: 'mobimart-b80a2',
    storageBucket: 'mobimart-b80a2.firebasestorage.app',
    iosBundleId: 'com.example.mobimartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlgJfzNwZcvFPKQAovCll24jsJK1k4-Hw',
    appId: '1:580060550825:ios:80dc606f8df9c072d67bb8',
    messagingSenderId: '580060550825',
    projectId: 'mobimart-b80a2',
    storageBucket: 'mobimart-b80a2.firebasestorage.app',
    iosBundleId: 'com.example.mobimartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwkbs224q8pKWwkHjSQ6mTnxMtwiPG34Y',
    appId: '1:580060550825:web:242c716e6b5afc59d67bb8',
    messagingSenderId: '580060550825',
    projectId: 'mobimart-b80a2',
    authDomain: 'mobimart-b80a2.firebaseapp.com',
    storageBucket: 'mobimart-b80a2.firebasestorage.app',
    measurementId: 'G-TCKVM3DMFZ',
  );

}